import React from 'react';

const FOOTER = () => {
    return (
        <div>
            <div className="col-md-5">
                <h1>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Nulla fugit tenetur, numquam eius nihil accusamus placeat velit incidunt atque sed praesentium laborum quaerat modi amet debitis, sit dolore! Velit perspiciatis debitis reprehenderit magni molestiae soluta, magnam harum ea laudantium earum eos accusamus, id ex illo impedit tenetur quibusdam consequuntur expedita?</h1>
            </div>
            <div className="col-md-2">
                <h1>Lorem, ipsum dolor sit amet consectetur adipisicing elit. Assumenda, tenetur.</h1>
            </div>
            <div className="col-md-2">lorem</div>
            <div className="col-md-3"></div>
        </div>
    );
};

export default FOOTER;